const CONFIG = {
  SSH_SERVER_PORT: 22,
  SSH_SERVER_USERNAME: process.env.SSH_SERVER_USERNAME,
  SSH_SERVER_PASSWORD: process.env.SSH_SERVER_PASSWORD,
  CONNECTION_LIMIT: 50,
  VALID_PORTS: [80, 443, 3001],
};

module.exports = CONFIG;
